name: Investrend
description: PT Buana Capital Sekuritas

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+87

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  async: ^2.8.1
  #######################################
  ##       NON NullSafety
  #######################################
  #auto_size_text: ^2.1.0
  #auto_size_text_field: ^0.1.7
  #carousel_slider: ^3.0.0
  #html_unescape: ^1.0.2
  #scrollable_positioned_list: ^0.1.10
  #firebase_core: 0.7.0
  #######################################
  ##      WITH NullSafety
  #######################################
  auto_size_text: ^3.0.0-nullsafety.0
  auto_size_text_field: ^1.0.1
  avatar_glow: ^2.0.2
  blurrycontainer: ^1.0.2
  cached_network_image: ^3.0.0
  camera: ^0.9.4+19
  carousel_slider: ^4.0.0
  #charts_flutter: ^0.10.0
  #charts_flutter: ^0.11.0
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  easy_localization: ^3.0.0
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.9
  fl_chart: ^0.36.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  #device_info_plus: ^3.2.1
  #webview_flutter: ^3.0.1
  flutter_html: ^2.2.1
  flutter_image_compress: ^1.1.0

  flutter_local_notifications: ^9.0.1
  #dartis: ^0.5.0
  flutter_locker: ^2.0.4
  flutter_riverpod: ^0.14.0+3
  flutter_sidekick: ^0.1.3
  flutter_slidable: ^0.6.0
  flutter_staggered_grid_view: ^0.4.0
  #flutter_webview_plugin: ^0.4.0
  flutter_widget_from_html: ^0.8.3
  fluttertoast: ^8.0.9
  form_field_validator: ^1.1.0
  html_unescape: ^2.0.0

  #  flutter_keyboard_visibility: ^4.0.4
  http: ^0.13.1
  image: ^3.0.2
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  jiffy: ^4.1.0
  like_button: ^2.0.2
  local_auth: ^1.1.11
  move_to_background: ^1.0.2

  package_info: ^2.0.2

  percent_indicator: ^3.0.1
  permission_handler: ^9.0.2
  photo_view: ^0.14.0
  reorderables: ^0.4.4
  scrollable_positioned_list: ^0.2.3
  search_choices: ^2.0.21

  #image_downloader: ^0.30.0
  #sqflite: ^2.0.0+4
  #path: ^1.8.0
  #badges: ^2.0.1
  share_plus: ^3.0.4
  shared_preferences: ^2.0.15
  #store_redirect: ^2.0.1
  skeleton_text: ^3.0.0
  syncfusion_flutter_charts: ^19.1.54
  #adaptive_theme: ^2.2.0
  #animated_theme_switcher: ^2.0.1
  #dynamic_theme: ^1.0.0
  syncfusion_flutter_signaturepad: ^19.4.56
  theme_manager: ^1.0.4
  #stack_trace: ^1.10.0
  #flutter_pdfview: ^1.2.1
  #url_launcher: ^6.0.10
  #url_launcher: ^6.0.12
  url_launcher: ^6.0.18
  video_player: ^2.2.17
  video_thumbnail: ^0.5.0
  #infinite_scroll_pagination: ^3.1.0
  #flip_card: ^0.5.0
  #  pull_to_refresh: ^2.0.0
  visibility_aware_state: ^1.0.3
  webview_flutter: ^2.8.0
  xml: ^5.1.0

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - translations/
    - images/
    - images/tabs_bottom/
    - images/icons/
    - images/sosmed/
    - images/backgrounds/
    - assets/index.html
    - assets/test.html
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Italic.ttf
          style: italic
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700

    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Italic.ttf
          style: italic
        - asset: fonts/TitilliumWeb-Regular.ttf
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 700

    - family: LobsterTwo
      fonts:
        - asset: fonts/LobsterTwo-Italic.ttf
          style: italic
        - asset: fonts/LobsterTwo-Regular.ttf
        - asset: fonts/LobsterTwo-Bold.ttf
          weight: 700
