import 'package:flutter/cupertino.dart';

class TradeDoneValue {
  String? time;
  int? noId;
  String? price;
  String? lot;
  String? fdBuy;
  String? buy;
  String? sell;
  String? fdSell;
  String? chg;
  String? percent;
  Color? color;
  bool isShown;

  TradeDoneValue({
    this.time,
    this.noId,
    this.price,
    this.lot,
    this.fdBuy,
    this.buy,
    this.sell,
    this.fdSell,
    this.chg,
    this.percent,
    this.color,
    this.isShown = true,
  });
  static List<TradeDoneValue> listDummy = [
    TradeDoneValue(
      time: '11:59:57',
      noId: 100,
      price: '6650',
      lot: '2',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:56',
      noId: 101,
      price: '6675',
      lot: '1',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+75',
      percent: '+1.13',
    ),
    TradeDoneValue(
      time: '11:59:56',
      noId: 102,
      price: '6500',
      lot: '1',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '-100',
      percent: '-2.13',
    ),
    TradeDoneValue(
      time: '11:59:56',
      noId: 103,
      price: '6675',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+75',
      percent: '+1.13',
    ),
    TradeDoneValue(
      time: '11:59:56',
      noId: 104,
      price: '6575',
      lot: '7',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '-25',
      percent: '-1.63',
    ),
    TradeDoneValue(
      time: '11:59:56',
      noId: 105,
      price: '6600',
      lot: '1',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '0',
      percent: '0',
    ),
    TradeDoneValue(
      time: '11:59:55',
      noId: 106,
      price: '6675',
      lot: '30',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+75',
      percent: '+1.13',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 100,
      price: '6675',
      lot: '2',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+75',
      percent: '+1.13',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 100,
      price: '6675',
      lot: '28',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+75',
      percent: '+1.13',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 100,
      price: '6600',
      lot: '4',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '0',
      percent: '0',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 112,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 120,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6600',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '0',
      percent: '0',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 101,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 103,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 104,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 105,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 106,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 107,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 110,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 101,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 103,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 105,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 106,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 104,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 103,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 103,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 103,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 106,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 106,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 106,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 105,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 105,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 107,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 107,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 107,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 107,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 102,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 104,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 104,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 104,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 113,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 113,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 115,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 111,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 115,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 109,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 109,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 108,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 142,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 129,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 125,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 109,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 109,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 109,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 109,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 110,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 105,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 104,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 103,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 103,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 103,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 108,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 108,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 108,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 115,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 115,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 115,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 123,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
    TradeDoneValue(
      time: '11:59:54',
      noId: 123,
      price: '6650',
      lot: '24',
      fdBuy: '-',
      buy: '--',
      sell: '--',
      fdSell: '-',
      chg: '+50',
      percent: '+0.75',
    ),
  ];
}
