-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVNdRqqP5OBcfWaig
evZRCGV5FpIlKsqpF4DsyCtfXaygCgYIKoZIzj0DAQehRANCAAQa2UvbZY52qtzc
g5SOjjYvnnZTXo9BPU1CS+L4p0Fi6SsTnf4PQ+1NpVpfEdwv3aBJYkIC8eMTncW8
pOic4CGu
-----END PRIVATE KEY-----